return {}
-- return {
--     "ray-x/lsp_signature.nvim",
--     event = "InsertEnter",
--     opts = {
--         bind = false,
--         handler_opts = {
--             border = "rounded",
--             floating_window = true, -- show hint in a floating window, set to false for virtual text only mode
--         },
--     },
-- config = function(_, opts)
--     require("lsp_signature").setup(opts)
-- end,
-- }
